// Generated by CoffeeScript 1.6.3
/*
Port of MicroEvent in Coffeescript with some naming modifications
and a new 'once' method.

Original project:
https://github.com/jeromeetienne/microevent.js
*/


(function() {
  var MicroEvent;

  MicroEvent = (function() {
    function MicroEvent() {}

    MicroEvent.prototype._init_event = function() {
      return this._listn || (this._listn = {});
    };

    MicroEvent.prototype._create_event = function(e) {
      return this._init_event()[e] || (this._init_event()[e] = []);
    };

    MicroEvent.prototype.on = function(e, f) {
      return (this._create_event(e)).push(f);
    };

    MicroEvent.prototype.off = function(e, f) {
      var t;
      if ((t = this._init_event()[e]) != null) {
        return t.splice(t.indexOf(f), 1);
      }
    };

    MicroEvent.prototype.once = function(e, f) {
      var t,
        _this = this;
      return this.on(e, (t = function() {
        return (_this.off(e, t)) && f.apply(_this, arguments);
      }));
    };

    MicroEvent.prototype.emit = function(e, p) {
      var l, t, _i, _len;
      if ((t = this._init_event()[e]) != null) {
        for (_i = 0, _len = t.length; _i < _len; _i++) {
          l = t[_i];
          l(p);
        }
      }
      return 0;
    };

    MicroEvent.include = function(t) {
      var p;
      for (p in this.prototype) {
        t.prototype[p] = this.prototype[p];
      }
      return 0;
    };

    MicroEvent.extend = function(obj) {
      var key, value;
      for (key in obj) {
        value = obj[key];
        this[key] = value;
      }
      return this;
    };

    return MicroEvent;

  })();

  module.exports = MicroEvent;

}).call(this);
